approval_policy = "never"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true
writable_roots = [
    "/Users/lordgrey/Library/Containers/com.liuliu.draw-things/Data/Documents/Models"
]
